site_name: 'Programming Languages: Principles and Paradigms'
site_author: 'Deian Stefan'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/PLSysSec/cse130-winter18'
    - type: 'twitter'
      link: 'https://twitter.com/deiandelmars'

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - footnotes
  - pymdownx.details:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - css/extra.css

pages:
  - About: index.md
  - Syllabus: syllabus.md
  - Organization: about.md
  - Contact information: contact.md
  - Lectures:
        - Week 1: 'lectures/week1/index.md'
        - Week 2: 'lectures/week2/index.md'
        - Week 3: 'lectures/week3/index.md'
        - Week 4: 'lectures/week4/index.md'
        - Week 5: 'lectures/week5/index.md'
        - Week 6: 'lectures/week6/index.md'
        - Week 7: 'lectures/week7/index.md'
        - Week 8: 'lectures/week8/index.md'
        - Week 9: 'lectures/week9/index.md'
  - Discussions:
        - Week 1: 'discussions/week1/index.md'
        - Week 2: 'discussions/week2/index.md'
  - Additional notes:
        - JavaScript No No's: 'notes/js_nono.md'
