site_name: 'Programming Languages: Principles and Paradigms'
site_author: 'Kaiser Pister'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  favicon: 'images/favicon.png'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/kpister/cse130-summer19'

markdown_extensions:
  - admonition
  - markdown_include.include:
      base_path: docs
  - footnotes
  - pymdownx.details:
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

extra_css:
  - css/extra.css

pages:
  - About: index.md
  - Syllabus: syllabus.md
  - Organization: about.md
  - Contact information: contact.md
  - Assignments: assignments.md
  - Lectures: 
    - Week 1: 'lectures/week1/index.md'
    - Week 1b: 'lectures/week1b/index.md'
    - Week 2a: 'lectures/week2a/index.md'
    - Week 2b: 'lectures/week2b/index.md'
    - Week 3b: 'lectures/week3b/index.md'
  - Discussions:
    - Week 1: 'discussions/week1/index.md'
    - Week 2: 'discussions/week2/index.md'
  - Additional notes:
    - JavaScript No No's: 'notes/js_nono.md'
